const hostelsData = [
  {
    id: 1,
    name: "Green Valley Hostel",
    fee: "₹5000/month",
    totalSeats: 20,
    emptyRooms: 5,
    address: "123 Main Street, Bengaluru",
    foodMenu: "Veg & Non-Veg, 3 meals a day",
    image: "https://source.unsplash.com/400x300/?hostel",
    phone: "+91 98765 43210",
    email: "greenvalley@gmail.com",
  },
  {
    id: 2,
    name: "Sunrise PG",
    fee: "₹4500/month",
    totalSeats: 25,
    emptyRooms: 8,
    address: "456 MG Road, Mumbai",
    foodMenu: "Only Veg, North & South Indian",
    image: "https://source.unsplash.com/400x300/?dormitory",
    phone: "+91 99887 65432",
    email: "sunrisepg@gmail.com",
  },
  {
    id: 3,
    name: "BlueSky Boys Hostel",
    fee: "₹4800/month",
    totalSeats: 30,
    emptyRooms: 10,
    address: "789 Park Lane, Pune",
    foodMenu: "Veg, 2 meals a day",
    image: "https://source.unsplash.com/400x300/?student-hostel",
    phone: "+91 91234 56789",
    email: "blueskyhostel@gmail.com",
  },
  {
    id: 4,
    name: "Elite Girls PG",
    fee: "₹5500/month",
    totalSeats: 18,
    emptyRooms: 3,
    address: "15 Residency Road, Delhi",
    foodMenu: "Non-Veg & Veg, 4 meals a day",
    image: "https://source.unsplash.com/400x300/?girls-hostel",
    phone: "+91 97654 32109",
    email: "elitepg@gmail.com",
  },
  {
    id: 5,
    name: "Royal Living Hostel",
    fee: "₹6000/month",
    totalSeats: 22,
    emptyRooms: 4,
    address: "33 Baker Street, Kolkata",
    foodMenu: "Veg & Non-Veg, unlimited meals",
    image: "https://source.unsplash.com/400x300/?hostel-room",
    phone: "+91 96543 21098",
    email: "royalliving@gmail.com",
  },
  {
    id: 6,
    name: "City View PG",
    fee: "₹5200/month",
    totalSeats: 28,
    emptyRooms: 7,
    address: "Lakeview Road, Hyderabad",
    foodMenu: "South Indian & North Indian",
    image: "https://source.unsplash.com/400x300/?pg-hostel",
    phone: "+91 98765 67890",
    email: "cityviewpg@gmail.com",
  },
  {
    id: 7,
    name: "Cozy Stay Hostel",
    fee: "₹4700/month",
    totalSeats: 35,
    emptyRooms: 12,
    address: "Hilltop Colony, Chennai",
    foodMenu: "Pure Veg, 3 meals a day",
    image: "https://source.unsplash.com/400x300/?bunk-beds",
    phone: "+91 87654 43210",
    email: "cozystay@gmail.com",
  },
  {
    id: 8,
    name: "Dream Living PG",
    fee: "₹5300/month",
    totalSeats: 20,
    emptyRooms: 5,
    address: "Sector 45, Noida",
    foodMenu: "Non-Veg & Veg, all meals included",
    image: "https://source.unsplash.com/400x300/?hostel-interior",
    phone: "+91 99876 54321",
    email: "dreamliving@gmail.com",
  },
  {
    id: 9,
    name: "Harmony Hostel",
    fee: "₹4900/month",
    totalSeats: 27,
    emptyRooms: 6,
    address: "Central Market, Jaipur",
    foodMenu: "Traditional Rajasthani Meals",
    image: "https://source.unsplash.com/400x300/?students-dorm",
    phone: "+91 90987 65432",
    email: "harmonyhostel@gmail.com",
  },
  {
    id: 10,
    name: "Golden Nest PG",
    fee: "₹5100/month",
    totalSeats: 22,
    emptyRooms: 4,
    address: "Beach Road, Goa",
    foodMenu: "Continental & Indian Meals",
    image: "https://source.unsplash.com/400x300/?modern-hostel",
    phone: "+91 96543 67890",
    email: "goldennestpg@gmail.com",
  }
];

export default hostelsData;
